# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0004_auto_20170222_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'required': 'Please provide your email address.'}, max_length=100),
        ),
    ]
