# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0005_auto_20170222_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'required': 'Please provide your email address.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'required': 'Please provide a unique username'}, max_length=50, unique=True),
        ),
    ]
