# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0006_auto_20170223_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventname',
            field=models.CharField(max_length=100),
        ),
    ]
