# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0007_auto_20170224_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn_text', models.CharField(max_length=200)),
                ('event_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventSystem.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventSystem.Question')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventSystem.User')),
            ],
        ),
    ]
