# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0008_question_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_value',
            field=models.CharField(default='', error_messages={'required': 'Please answer the question'}, max_length=200),
        ),
    ]
