# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0009_response_response_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='plus_ones',
            field=models.BooleanField(default=False),
        ),
    ]
