# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0010_event_plus_ones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='plus_ones',
            new_name='plus_one',
        ),
        migrations.AddField(
            model_name='question',
            name='visible_to',
            field=models.ManyToManyField(related_name='visble_to', to='eventSystem.User'),
        ),
        migrations.AddField(
            model_name='response',
            name='for_plus_one',
            field=models.BooleanField(default=False),
        ),
    ]
