# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0011_auto_20170225_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventSystem.Question')),
            ],
            bases=('eventSystem.question',),
        ),
        migrations.CreateModel(
            name='ChoiceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_plus_one', models.BooleanField(default=False)),
                ('response_value', models.NullBooleanField()),
                ('choice_id', models.PositiveSmallIntegerField()),
                ('qn_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventSystem.ChoiceQuestion')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventSystem.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Response',
            new_name='OpenResponse',
        ),
    ]
