# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0012_auto_20170225_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('qn_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventSystem.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='choicequestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='choiceresponse',
            name='choice_id',
        ),
        migrations.AlterField(
            model_name='choiceresponse',
            name='qn_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventSystem.Question'),
        ),
        migrations.DeleteModel(
            name='ChoiceQuestion',
        ),
        migrations.AddField(
            model_name='choiceresponse',
            name='choice_for',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventSystem.Choice'),
        ),
    ]
