# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0013_auto_20170225_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='plus_one',
            new_name='plus_ones',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='choiceresponse',
            name='choice_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventSystem.Choice'),
        ),
    ]
