# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0013_auto_20170225_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceresponse',
            name='choice_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventSystem.Choice'),
        ),
    ]
