# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0014_auto_20170228_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='visible_to',
            field=models.ManyToManyField(related_name='visible_to', to='eventSystem.User'),
        ),
    ]
