# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0016_auto_20170302_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceresponse',
            name='response_value',
            field=models.ManyToManyField(related_name='choices', to='eventSystem.Choice'),
        ),
    ]
