# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0017_auto_20170302_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiceresponse',
            name='choice_for',
        ),
    ]
