# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0018_remove_choiceresponse_choice_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
