# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventSystem', '0019_question_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_plus_ones',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='event',
            name='plus_ones',
        ),
        migrations.AddField(
            model_name='event',
            name='plus_ones',
            field=models.ManyToManyField(related_name='plus_ones', to='eventSystem.User'),
        ),
    ]
